version: '3.8'

services:
  redhat-server:
    image: registry.access.redhat.com/ubi8/ubi:latest
    tty: true
    ports:
      - "80:80"     # Mapea el puerto 80 del contenedor al puerto 80 del host
      - "443:443"   # Mapea el puerto 443 del contenedor al puerto 443 del host
    networks:
      - my_bridge_network

networks:
  my_bridge_network:
    driver: bridge
